modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-BoneTorch/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sbm-bone-torch"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="bonetorch" #mandatory
version="0.0.1" #mandatory
displayName="[SBM] BoneTorch" #mandatory
description='''Simple mod to create torches from bones''' #mandatory

[[dependencies.bonetorch]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bonetorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"